version: '3'
services:
  nginx-router:
    build:
      context: ./nginx-router
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    restart: always
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./api-gateway:/app
