version: '3'
services:

  # Router
  nginx-router:
    build:
      context: ./nginx-router
    ports:
      - '3000:3000'

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    environment:
      - PORT=8000
      - AUTHENTICATION_HOST=authentication
      - AUTHENTICATION_PORT=8000
      - PLACE_HOST=place
      - PLACE_PORT=8000
      - RESERVATION_HOST=reservation
      - RESERVATION_PORT=8000
      - REVIEW_HOST=review
      - REVIEW_PORT=8000
    # Development Options
    # command: ['npm', 'run', 'dev']
    # volumes:
    #   - /app/node_modules
    #   - ./api-gateway:/app

  # Authentication Service
  authentication:
    build:
      context: ./authentication
    environment:
      - PORT=8000
      - MONGO_HOST=mongo-db
      - MONGO_PORT=27017
      - MONGO_DATABASE=authentication
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - DEFAULT_PROFILE_IMG=/static/defaults/profile.jpg
      - JWT_SECRET=MT9UYrjqDptFCkZPGRxUNFgq6NIIfr21zRZIiaofcNnB5AkfJEqJyMxgxWcq
      - STORAGE_HOST=storage
      - STORAGE_PORT=8000
    # Development Options
    # command: ['npm', 'run', 'dev']
    # volumes:
    #   - /app/node_modules
    #   - ./authentication:/app

  # Place Management Service
  place:
    build:
      context: ./place
    environment:
      - PORT=8000
      - MONGO_HOST=mongo-db
      - MONGO_PORT=27017
      - MONGO_DATABASE=place
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - DEFAULT_PLACEHOLDER_IMG=/static/defaults/placeholder.jpg
      - STORAGE_HOST=storage
      - STORAGE_PORT=8000
    # Development Options
    # command: ['npm', 'run', 'dev']
    # volumes:
    #   - /app/node_modules
    #   - ./place:/app

  # Reservation Service
  reservation:
    build:
      context: ./reservation
    environment:
      - PORT=8000
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=chowspace
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
      - PLACE_HOST=place
      - PLACE_PORT=8000
    # Development Options
    # command: ['npm', 'run', 'dev']
    # volumes:
    #   - /app/node_modules
    #   - ./reservation:/app

  # Review Service
  review:
    build:
      context: ./review
    environment:
      - PORT=8000
      - MONGO_HOST=mongo-db
      - MONGO_PORT=27017
      - MONGO_DATABASE=review
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - RESERVATION_HOST=reservation
      - RESERVATION_PORT=8000
      - PLACE_HOST=place
      - PLACE_PORT=8000
    # Development Options
    # command: ['npm', 'run', 'dev']
    # volumes:
    #   - /app/node_modules
    #   - ./review:/app
    # ports:
    #   - '8000:8000'

  # Storage Service
  storage:
    build:
      context: ./storage
    environment:
      - PORT=8000
      - MONGO_HOST=mongo-db
      - MONGO_PORT=27017
      - MONGO_DATABASE=storage
      - MONGO_USER=root
      - MONGO_PASSWORD=example
    # Development Options
    # command: ['npm', 'run', 'dev']
    # volumes:
    #   - /app/node_modules
    #   - ./storage:/app

  # Databases
  mongo-db:
    image: mongo:4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    # Development Options
    ports:
      - '27017:27017'

  postgres-db:
    image: postgres:11
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=chowspace
    # Development Options
    ports:
      - '5432:5432'
