version: '3'
services:
  nginx-router:
    build:
      context: ./nginx-router
    ports:
      - '3000:3000'
  api-gateway:
    build:
      context: ./api-gateway
    command: ['npm', 'run', 'dev']
    environment:
      - PORT=8000
      - AUTHENTICATION_HOST=authentication
      - AUTHENTICATION_PORT=3000
  authentication:
    build:
      context: ./authentication
    command: ['npm', 'run', 'dev']
    environment:
      - PORT=3000
      - MONGO_HOST=authentication-db
      - MONGO_PORT=27017
      - MONGO_DATABASE=authentication
      - MONGO_USER=root
      - MONGO_PASSWORD=example
  authentication-db:
    image: mongo:4
    ports:
      - '30001:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
