module.exports ={
    PORT: process.env.PORT,
    POSTGRES_HOST: process.env.POSTGRES_HOST,
    POSTGRES_PORT: process.env.POSTGRES_PORT,
    POSTGRES_DATABASE: process.env.POSTGRES_DATABASE,
    POSTGRES_USER: process.env.POSTGRES_USER,
    POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD,
    PLACE_HOST: process.env.PLACE_HOST,
    PLACE_PORT: process.env.PLACE_PORT,
    RABBITMQ_DEFAULT_USER: process.env.RABBITMQ_DEFAULT_USER,
    RABBITMQ_DEFAULT_PASS: process.env.RABBITMQ_DEFAULT_PASS,
    RABBITMQ_HOST: process.env.RABBITMQ_HOST,
    RABBITMQ_PORT: process.env.RABBITMQ_PORT
};
