module.exports = {
    PORT: process.env.PORT,
    AUTHENTICATION_HOST: process.env.AUTHENTICATION_HOST,
    AUTHENTICATION_PORT: process.env.AUTHENTICATION_PORT,
    PLACE_HOST: process.env.PLACE_HOST,
    PLACE_PORT: process.env.PLACE_PORT,
    RESERVATION_HOST: process.env.RESERVATION_HOST,
    RESERVATION_PORT: process.env.RESERVATION_PORT
};
