module.exports = {
    PORT: process.env.PORT,
    MONGO_HOST: process.env.MONGO_HOST,
    MONGO_PORT: process.env.MONGO_PORT,
    MONGO_DATABASE: process.env.MONGO_DATABASE,
    MONGO_USER: process.env.MONGO_USER,
    MONGO_PASSWORD: process.env.MONGO_PASSWORD,
    DEFAULT_PLACEHOLDER_IMG: process.env.DEFAULT_PLACEHOLDER_IMG,
    STORAGE_HOST: process.env.STORAGE_HOST,
    STORAGE_PORT: process.env.STORAGE_PORT,
    RABBITMQ_DEFAULT_USER: process.env.RABBITMQ_DEFAULT_USER,
    RABBITMQ_DEFAULT_PASS: process.env.RABBITMQ_DEFAULT_PASS,
    RABBITMQ_HOST: process.env.RABBITMQ_HOST,
    RABBITMQ_PORT: process.env.RABBITMQ_PORT
};
